/**
 * The status line wrapper.
 *
 * Claude Code gives a status line command one chance to print, debounces updates
 * at 300 ms, and cancels the script still running when a new update arrives. So
 * this wrapper has exactly one job beyond forwarding data: get out of the way.
 *
 * It prints whatever the user's own status line printed, unchanged. If Mirante's
 * daemon is down, that still happens — a stopped Mirante must never degrade a
 * Claude Code session.
 *
 * The token lives in a 0600 file next to this script rather than on the command
 * line, where every process on the machine could read it from the process table.
 */
export const statusLineWrapperSource = (configPath: string): string => `#!/usr/bin/env node
// Generated by Mirante. Safe to delete once 'mirante uninstall' has run.
import { readFileSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import http from 'node:http';

const CONFIG_PATH = ${JSON.stringify(configPath)};
const HEARTBEAT_PATH = CONFIG_PATH.replace(/statusline\.json$/, 'statusline-last-run');

const readStdin = () => {
  try {
    return readFileSync(0, 'utf8');
  } catch {
    return '';
  }
};

const input = readStdin();

let config = {};
try {
  config = JSON.parse(readFileSync(CONFIG_PATH, 'utf8'));
} catch {
  // No config means no daemon to talk to. Fall through and still print.
}

// The user's status line comes first and is never made to wait on us.
if (config.originalCommand) {
  try {
    const result = spawnSync(config.originalCommand, {
      shell: true,
      input,
      encoding: 'utf8',
      timeout: 3000,
    });
    if (result.stdout) process.stdout.write(result.stdout);
  } catch {
    // A broken original command is the user's to fix; we do not mask it with ours.
  }
} else {
  try {
    const data = JSON.parse(input);
    const model = data?.model?.display_name ?? '';
    const context = data?.context_window?.used_percentage;
    const parts = [model, context === undefined ? '' : context + '% ctx'].filter(Boolean);
    if (parts.length > 0) process.stdout.write(parts.join(' · '));
  } catch {
    // Nothing printable. An empty status line beats a crash.
  }
}

// A heartbeat, written whether or not the daemon is listening. It is the only
// way to tell "Claude Code never called the status line" apart from "it called
// it and nobody was home" — two situations that look identical from the daemon.
try {
  writeFileSync(HEARTBEAT_PATH, new Date().toISOString(), { mode: 0o600 });
} catch {
  // A missing heartbeat costs a diagnostic, not the status line.
}

if (config.daemonUrl && config.token && input) {
  try {
    const url = new URL(config.daemonUrl + '/ingest/statusline');
    const request = http.request(
      {
        host: url.hostname,
        port: url.port,
        path: url.pathname,
        method: 'POST',
        headers: {
          'content-type': 'application/json',
          'content-length': Buffer.byteLength(input),
          authorization: 'Bearer ' + config.token,
        },
      },
      (response) => response.resume(),
    );
    // Hard cap. Whatever happens, this script is finished with the daemon quickly.
    request.setTimeout(400, () => request.destroy());
    request.on('error', () => {});
    request.end(input);
  } catch {
    // Daemon down, port changed, anything: none of it is the user's problem.
  }
}
`;

export type StatusLineWrapperConfig = {
  daemonUrl: string;
  token: string;
  /** The command Mirante wrapped, or null when there was none. */
  originalCommand: string | null;
};
